# Name of the speller package in various languages.
# The default is English + autonym:
[speller.name]
en = "Southern Lushootseed spellchecker"
slh = "Autonym spellchecker"

# Description of the speller package in various languages.
# The default is English + autonym:
[speller.description]
en = "A spellchecker for Southern Lushootseed, made by members of the language community, and by the Divvun and Giellatekno groups at UiT The Arctic University of Norway"
slh = "TRANSLATE: A spellchecker for Southern Lushootseed, made by members of the language community, and by the Divvun and Giellatekno groups at UiT The Arctic University of Norway"

[macos]
system_pkg_id = "no.divvun.MacDivvun.slh"

[windows]
system_product_code = "{610ECE22-C9A6-4FA9-A333-5A12EEBA6CD0}_is1"

[package.speller]
name = "Southern Lushootseed"
version = "0.1.0"

[package.grammar]
name = "Southern Lushootseed"
version = "0.1.0"

[package.tts-text-proc]
name = "Southern Lushootseed"
version = "0.1.0"
