template = "https://github.com/giellalt/template-lang-und"
rev_id = 265
template_sha = "55c74340aa57ef2b38d3f84b2a9790e969781f56"

[replacements]
__GLOTTOLOG_ID__ = "sout2965"
__LICENSE__ = "LGPLv3"
__REPO__ = "lang-slh"
__UND2C__ = "slh"
__UNDEFINED__ = "Southern Lushootseed"
__UND__ = "slh"
